"""vacancy_dates

Revision ID: bbc26f49e39e
Revises: e64ab4a777a1
Create Date: 2024-05-14 13:22:46.288975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc26f49e39e'
down_revision: Union[str, None] = 'e64ab4a777a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('date_uploaded', sa.TIMESTAMP(), nullable=False))
    op.add_column('vacancy', sa.Column('date_disappeared', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'date_disappeared')
    op.drop_column('vacancy', 'date_uploaded')
    # ### end Alembic commands ###
